CREATE TABLE IF NOT EXISTS `segment_efforts` (
	`id` text PRIMARY KEY NOT NULL,
	`segment_id` text NOT NULL,
	`activity_id` text NOT NULL,
	`attempt_index` integer NOT NULL,
	`source` text NOT NULL,
	`start_record_index` integer NOT NULL,
	`end_record_index` integer NOT NULL,
	`start_distance_meters` real,
	`end_distance_meters` real,
	`start_time` integer,
	`end_time` integer,
	`distance_meters` real,
	`elapsed_seconds` real,
	`moving_seconds` real,
	`average_speed_meters_per_second` real,
	`max_speed_meters_per_second` real,
	`average_heart_rate_bpm` real,
	`max_heart_rate_bpm` integer,
	`elevation_gain_meters` real,
	`elevation_loss_meters` real,
	`vam_meters_per_hour` real,
	`average_cadence_rpm` real,
	`average_power_watts` real,
	`normalized_power_watts` real,
	`coverage_ratio` real NOT NULL,
	`confidence` real NOT NULL,
	`average_deviation_meters` real,
	`max_deviation_meters` real,
	`computed_at` integer NOT NULL,
	FOREIGN KEY (`segment_id`) REFERENCES `segments`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `segment_efforts_segment_activity_attempt_idx` ON `segment_efforts` (`segment_id`,`activity_id`,`attempt_index`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `segment_efforts_activity_idx` ON `segment_efforts` (`activity_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `segment_efforts_segment_elapsed_idx` ON `segment_efforts` (`segment_id`,`elapsed_seconds`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `segments` (
	`id` text PRIMARY KEY NOT NULL,
	`source_activity_id` text NOT NULL,
	`name` text NOT NULL,
	`source` text DEFAULT 'manual' NOT NULL,
	`sport` text,
	`start_record_index` integer NOT NULL,
	`end_record_index` integer NOT NULL,
	`start_distance_meters` real,
	`end_distance_meters` real,
	`start_time` integer,
	`end_time` integer,
	`start_latitude` real,
	`start_longitude` real,
	`end_latitude` real,
	`end_longitude` real,
	`distance_meters` real,
	`elapsed_seconds` real,
	`moving_seconds` real,
	`average_speed_meters_per_second` real,
	`max_speed_meters_per_second` real,
	`average_heart_rate_bpm` real,
	`max_heart_rate_bpm` integer,
	`elevation_gain_meters` real,
	`elevation_loss_meters` real,
	`vam_meters_per_hour` real,
	`average_cadence_rpm` real,
	`average_power_watts` real,
	`normalized_power_watts` real,
	`geometry_json` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`source_activity_id`) REFERENCES `activities`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `segments_source_activity_idx` ON `segments` (`source_activity_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `segments_sport_idx` ON `segments` (`sport`);